import type { Metadata } from 'next';
import { montserrat } from '@/styles/fonts';
import '../styles/globals.css';
import Footer from '@/components/layout/footer/Footer/Footer';
import Header from '@/components/layout/header/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/logo.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/logo.png" />
      </head>
      <body className={`${montserrat.className} antialiased`}>
        <Header />
        <main id="main-content" className="container min-h-screen">
          {children}
        </main>
        <div id="modal-container" />
        <Footer />
      </body>
    </html>
  );
}
