import type { Metadata } from 'next';
import { montserrat } from '@/styles/fonts';
import '../styles/globals.css';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/header/Header/Header';

export const metadata: Metadata = {
  title: 'Мирний воїн',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.ico'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Header />
        <main className="container min-h-screen">{children}</main>
        <div id="modal-container" />
        <Footer />
      </body>
    </html>
  );
}
